CC=nvcc 


main.out: mkClockMeasure.h mkCuda.h main.cpp
	$(CC) -o ./makefiles/sphere_6_20_400_low_epsilon.out main.cpp
	$ ./makefiles/sphere_6_20_400_low_epsilon.out

clean:
	rm -rf./makefiles/sphere_6_20_400_low_epsilon.out
